# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = 'spreadsheetx'
  s.version = '0.2.2'

  s.required_rubygems_version = Gem::Requirement.new('>= 0') if s.respond_to? :required_rubygems_version=
  s.authors = ['Craig Ulliott']
  s.date = '2011-07-09'
  s.description = 'Using an existing xlsx file as a template, it allows you to modify cell values and add rows and columns.  Facilitating a templateized approach to creating a new xlsx spreadsheet'
  s.email = 'craigulliott@gmail.com'
  s.extra_rdoc_files = [
    'LICENSE.txt',
    'README.rdoc'
  ]
  s.files = [
    '.document',
    '.rspec',
    'Gemfile',
    'Gemfile.lock',
    'LICENSE.txt',
    'README.rdoc',
    'Rakefile',
    'VERSION',
    'lib/spreadsheetx.rb',
    'lib/spreadsheetx/cell_format.rb',
    'lib/spreadsheetx/workbook.rb',
    'lib/spreadsheetx/worksheet.rb',
    'spec/spec_helper.rb',
    'spec/spreadsheetx_spec.rb',
    'spreadsheetx.gemspec',
    'templates/spec.xlsx'
  ]
  s.homepage = 'http://github.com/craigulliott/spreadsheetx'
  s.licenses = ['MIT']
  s.require_paths = ['lib']
  s.rubygems_version = '1.6.2'
  s.summary = 'Facilitates opening and modifying existing xlsx excel spreadsheets'

  s.specification_version = 3

  s.add_runtime_dependency('libxml-ruby', ['~> 3.1.0'])
  s.add_runtime_dependency('zipruby', ['~> 0.3.6'])
  s.add_development_dependency('bundler', ['~> 1.0.0'])
  s.add_development_dependency('jeweler', ['~> 1.6.2'])
  s.add_development_dependency('rcov', ['>= 0'])
  s.add_development_dependency('rspec', ['~> 2.3.0'])
end
